name: Test Paths

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/**'
  workflow_dispatch:
    inputs:
      deploy_target:
        description: 'Test'
        type: choice
        options:
          - all

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: test-paths-deploy
      cancel-in-progress: true
    steps:
      - run: echo "paths test works"
